### ISSUE TITLE
[Suggestion] Only logs fields that have been modified

### ISSUE THREAD

**Issue by JeremieBergeron** [yungts97/laravel-user-activity-log#3]
Let's suppose I have a table that has these column:
- ID
- name
- price
- description
- id_event

Then, I edit the field name and price in a view.

**Currently**: logs->data will contain all the data of the record.
**What I would like to have**: logs->data would only contains the name and the price. It could be an option.

**Comment by yungts97** [comment]
Thanks for the suggestion, I have also received a similar suggestion from others. I considered making it in the next version.

**Comment by JeremieBergeron** [comment]
Thank you. Since you closed the other request about it, I did not see it: https://github.com/yungts97/laravel-user-activity-log/issues/2

**Comment by TheNewSound** [comment]
`$model->getChanges()` would work I think

**Comment by yungts97** [comment]
> `$model->getChanges()` would work I think

Sorry for the late response, I want to clarify about how the logger records for "Edit". The logger for `Edit` will only log the original field values of the `Loggable` model. This allows having a history for us to keep track of how the model fields have been modified.  

For example, you have a `Product` model that has these columns:
- ID
- name
- price
- description

Scenario:
1. Firstly, you changed the product's `name`. (Log 1)
2. After that, you decided to change the product's `price`. (Log 2)
3. And we have 2 logs for the product now.
4. You can get a product's logs by `$product->logs()` and compare the differences between the current product fields with the product log fields. Like this `current_product ` ->`log2`-> `log1` and so on .

**Comment by yungts97** [comment]
I will consider making a function to conveniently track the changes in the loggable model. Please let me know if you have any ideas. Thank you.

**Comment by JeremieBergeron** [comment]
I'm not sure if you're saying you're going to keep logging all the fields.

If I would want to offer a modification history for the client, it is much more practical to log only the fields that have been modified and not all the fields and compare each log with the previous log.
It takes much less space in the database.

**Comment by yungts97** [comment]
Yes, you're right. Only logs modified fields instead of all fields, it could be saved much space. 
I used back the previous scenario again and try to express what you mean. 
So, you mean like Log1 only logs the **original** `name` field, while Log 2 only the **original** `price` field?

Is that what you mean?

**Comment by JeremieBergeron** [comment]
> So, you mean like Log1 only logs the original name field, while Log 2 only the original price field?
Yes, exactly.

I don't see in which case it would be better to copy all the field.
another example: 

1. You changed the product's name and the description at the same time.
2. You save.
3. Only one logs will be saved and this logs would all the field that have been modified (in this example, name && description)

What do you think about this idea?

**Comment by yungts97** [comment]
> What do you think about this idea?

Yup. This is what I wanna make clear to you. But it' could be better to make it optional.  So anytime, you can change to log only modified fields or all fields.

**Comment by yungts97** [comment]
This feature is available now with https://github.com/yungts97/laravel-user-activity-log/commit/f0518ede14ab61d245be70e4cffc81e73abdc956. I'll close this issue.
