### ISSUE TITLE
add show events in user-activity-log

### ISSUE THREAD

**Issue by maxdiable** [yungts97/laravel-user-activity-log#4]
hi,
it's possible to add show event in user-activity-log?

 'events' => [
        'create' => true,
        'edit'   => true,
        'delete' => true,
        'login'  => true,
        'show'  => true,
        'logout' => true
    ],

br
Max

**Comment by yungts97** [comment]
Thanks for the suggestion. This feature will be added in the next version. The next version will be released this month.

**Comment by yungts97** [comment]
This feature is available now with https://github.com/yungts97/laravel-user-activity-log/commit/f0518ede14ab61d245be70e4cffc81e73abdc956. I'll close this issue.
