### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by rabol** [yungts97/laravel-user-activity-log#6]
**Describe the bug**

Database seeding does not work

**To Reproduce**
1. ```php artisan db:seed```

**Expected behavior**
That no exception is thrown

**Comment by yungts97** [comment]
Thanks for opening the issue on our project! We appreciate your feedback and will look into the issue and keep you updated. Your contribution is valuable, and we welcome any further suggestions or feedback. Thank you!

**Comment by yungts97** [comment]
Hello @rabol, if I'm not mistaken, the model you're seeding is using the Loggable trait and it's trying to log user activity. However, the authenticated user doesn't exist in your seeder. For your situation, I suggest you wrap `withoutEvent::()` method to your model to avoid triggering Loggable events.
```php
YourModel::withoutEvents(function(){
     YourModel::factory()->create();
});
```
