### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ItsVaidas** [yungts97/laravel-user-activity-log#7]
**Describe the bug**
When you have two or more User models and define in the migration that user is Admin model, when User model logins, it still tries to insert into table that action. In return, it fails, because User id is 4, but Admin is only 1

**To Reproduce**
Explained previosly

**Expected behavior**
Only log one user action or have the ability to have multiple user ids to seperate columns and define it in config

**Screenshots**
(It says - register)
![image](https://github.com/user-attachments/assets/dedbb12e-1b32-4a90-96c2-bb800626ba8b)

**Desktop (please complete the following information):**
 - Windows
 - Edge
 - 11

**Comment by yungts97** [comment]
Hi @ItsVaidas, this issue has been fixed in the [v1.4.2 latest version](https://github.com/yungts97/laravel-user-activity-log/releases/tag/v1.4.2). Please update to the latest version, and the problem should be resolved.

**Comment by yungts97** [comment]
For the multiple user models' logger feature, I will consider adding it in the next version.
